version: '3.4'

services:
  registration:
    image: fluffyspoon.registration
    build:
      dockerfile: src/fluffyspoon.registration/Dockerfile
      context: ..
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - Orleans__MembershipProvider__Address=http://consul:8500
    depends_on:
      - consul

  consul:
    image: consul:latest
    command: "agent -server -bootstrap -ui -client 0.0.0.0"
    ports:
      - "8500:8500"